# Generated by Django 6.0.1 on 2026-03-07 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('drive_date', models.DateField()),
                ('location_or_link', models.CharField(help_text='Venue address or online meeting link', max_length=500)),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='companies.companyprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_drives', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(blank=True, help_text='Optional: link to a specific job', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drives', to='companies.job')),
            ],
            options={
                'ordering': ['-drive_date', '-created_at'],
            },
        ),
    ]
