# Generated by Django 6.0.1 on 2026-03-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hiring_flow',
            field=models.CharField(choices=[('applications', 'Application review (shortlist & rounds)'), ('drive', 'Drive (schedule campus drive)'), ('both', 'Both (drive + application review)')], default='applications', help_text='How the company wants to process applications for this job', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='interview_rounds',
            field=models.JSONField(blank=True, default=list, help_text="Ordered list of interview round keys (e.g. ['resume_shortlist','technical','hr','final'])"),
        ),
    ]
