# Generated by Django 6.0.1 on 2026-03-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_job_workflow_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='client_images',
            field=models.JSONField(blank=True, default=list, help_text='List of Cloudinary image URLs'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='specialities',
            field=models.TextField(blank=True, help_text='Comma-separated or line-separated specialities'),
        ),
    ]
