# Generated by Django 6.0.1 on 2026-03-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companyprofile_client_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='min_10th_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='min_12th_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
