# Generated by Django 6.0.1 on 2026-03-07 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('selected', 'Selected')], default='applied', max_length=20)),
                ('current_round', models.CharField(blank=True, choices=[('resume_shortlist', 'Resume Shortlisting'), ('aptitude', 'Aptitude Test'), ('technical', 'Technical Interview'), ('hr', 'HR Interview'), ('final', 'Final Selection')], default='resume_shortlist', max_length=30)),
                ('round_notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='companies.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-applied_at'],
                'unique_together': {('job', 'student')},
            },
        ),
    ]
