# Generated by Django 6.0.1 on 2026-03-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='attended',
            field=models.BooleanField(default=False, help_text='Did the student attend the drive?'),
        ),
    ]
