# Generated by Django 6.0.1 on 2026-03-07 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('roll_number', models.CharField(max_length=50, unique=True)),
                ('passing_year', models.PositiveIntegerField(blank=True, null=True)),
                ('marks_10th', models.DecimalField(blank=True, decimal_places=2, help_text='10th standard marks (percentage)', max_digits=5, null=True)),
                ('marks_12th', models.DecimalField(blank=True, decimal_places=2, help_text='12th standard marks (percentage)', max_digits=5, null=True)),
                ('diploma_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('current_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('skills', models.TextField(blank=True, help_text='Comma-separated or line-separated skills')),
                ('resume_url', models.URLField(blank=True, help_text='Cloudinary URL', max_length=500)),
                ('placement_status', models.CharField(choices=[('unplaced', 'Unplaced'), ('placed', 'Placed')], default='unplaced', max_length=20)),
                ('placed_company_name', models.CharField(blank=True, max_length=200)),
                ('data_verified', models.BooleanField(default=False, help_text='Student has confirmed their data is correct')),
                ('job_alerts_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.course')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
