# Generated by Django 6.0.1 on 2026-03-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='enrollment_number',
            field=models.CharField(blank=True, help_text='University enrollment / registration number', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='location',
            field=models.CharField(blank=True, help_text='Preferred job location / current city', max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='past_education',
            field=models.TextField(blank=True, help_text='Previous education history (institutes, programs, years)'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pursuing_degree',
            field=models.CharField(blank=True, help_text='Current degree/program being pursued', max_length=200),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
