# Generated by Django 6.0.1 on 2026-03-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_studentprofile_address_studentprofile_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='past_education',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='pursuing_degree',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='state',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='education_history',
            field=models.TextField(blank=True, help_text='Past education history / projects / experience for resume'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='permanent_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='enrollment_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
