# Generated by Django 6.0.1 on 2026-03-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_studentprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profile_picture',
            field=models.URLField(blank=True, help_text='Cloudinary URL', max_length=500),
        ),
    ]
