# Generated by Django 6.0.1 on 2026-03-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Your Institute Name', max_length=200)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('logo_url', models.URLField(blank=True, max_length=500)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('placement_email', models.EmailField(blank=True, max_length=254)),
                ('primary_color', models.CharField(blank=True, help_text='Optional primary color (hex or Tailwind token)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Institute configuration',
                'verbose_name_plural': 'Institute configuration',
            },
        ),
    ]
