# Generated by Django 6.0.1 on 2026-03-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_instituteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='instituteconfig',
            name='address',
            field=models.CharField(blank=True, help_text='Institute address for footer', max_length=300),
        ),
        migrations.AddField(
            model_name='instituteconfig',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone for footer', max_length=50),
        ),
        migrations.AddField(
            model_name='instituteconfig',
            name='opportunities',
            field=models.CharField(default='500+', help_text='Total opportunities (e.g. 500+)', max_length=50),
        ),
        migrations.AddField(
            model_name='instituteconfig',
            name='partner_companies',
            field=models.CharField(default='85+', help_text='Partner companies count (e.g. 85+)', max_length=50),
        ),
        migrations.AddField(
            model_name='instituteconfig',
            name='placement_rate',
            field=models.CharField(default='90%', help_text='Placement rate (e.g. 90%)', max_length=50),
        ),
        migrations.AddField(
            model_name='instituteconfig',
            name='students_count',
            field=models.CharField(default='1200+', help_text='Total students (e.g. 1200+)', max_length=50),
        ),
        migrations.AddField(
            model_name='instituteconfig',
            name='students_every_year',
            field=models.CharField(default='300+', help_text='Students graduating every year (e.g. 300+)', max_length=50),
        ),
    ]
