# Generated by Django 6.0.1 on 2026-03-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_add_institute_stats_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('link', 'Direct Link'), ('pdf', 'PDF Document'), ('file', 'Other File')], default='link', max_length=20),
        ),
    ]
